NAME=array
CUSTOM_MODULE_SCHEDULING = 1
ifeq ($(NO_OPT),)
	NO_OPT=0
endif
ifeq ($(NO_INLINE),)
	NO_INLINE=0
endif
LOCAL_CONFIG = -legup-config=config.tcl
LEVEL = ..
include $(LEVEL)/Makefile.myDocMyHell
