NAME=array
CUSTOM_MODULE_SCHEDULING = 1

ifeq ($(NO_OPT),)
	NO_OPT=1
endif
ifeq ($(NO_INLINE),)
	NO_INLINE=1
endif
LEVEL = ..

LOCAL_CONFIG = -legup-config=config.tcl
include $(LEVEL)/Makefile.myDocMyHell
