//----------------------------------------------------------------------------//
// Generated by LegUp High-Level Synthesis Tool Version 4.0 (http://legup.org)
// Compiled: Mon Jun  4 15:32:40 2018
// University of Toronto
// For research and academic purposes only. Commercial use is prohibited.
// Please send bugs to: legup@eecg.toronto.edu
// Date: Fri Aug  3 15:38:46 2018
//----------------------------------------------------------------------------//

`define MEMORY_CONTROLLER_ADDR_SIZE 32
`define MEMORY_CONTROLLER_DATA_SIZE 64
// Number of RAM elements: 1
`define MEMORY_CONTROLLER_TAG_SIZE 9

// Turn off warning 'ignoring unsupported system task'
// altera message_off 10175

`timescale 1 ns / 1 ns
module top
	(
		clk,
		reset,
		start,
		finish,
		waitrequest,
		return_val
	);
input clk;
input reset;
input start;
output wire finish;
input waitrequest;
output wire [31:0] return_val;
/* synthesis translate_off */
assign memory_controller_waitrequest = waitrequest;
/* synthesis translate_on */

main main_inst(
	.clk( clk ),
	.clk2x( clk2x ),
	.clk1x_follower( clk1x_follower ),
	.reset( reset ),
	.start( start ),
	.finish( finish ),
	.return_val( return_val ),
	.memory_controller_waitrequest(memory_controller_waitrequest)
);

endmodule

`timescale 1 ns / 1 ns
module main
(
	clk,
	clk2x,
	clk1x_follower,
	reset,
	start,
	finish,
	memory_controller_waitrequest,
	return_val
);

parameter [5:0] LEGUP_0 = 6'd0;
parameter [5:0] LEGUP_F_main_BB_preheader2_1 = 6'd1;
parameter [5:0] LEGUP_F_main_BB_preheader2_2 = 6'd2;
parameter [5:0] LEGUP_F_main_BB_preheader2_3 = 6'd3;
parameter [5:0] LEGUP_F_main_BB_preheader2_4 = 6'd4;
parameter [5:0] LEGUP_F_main_BB_preheader2_5 = 6'd5;
parameter [5:0] LEGUP_F_main_BB_preheader2_6 = 6'd6;
parameter [5:0] LEGUP_F_main_BB_preheader2_7 = 6'd7;
parameter [5:0] LEGUP_F_main_BB__13_8 = 6'd8;
parameter [5:0] LEGUP_F_main_BB__13_9 = 6'd9;
parameter [5:0] LEGUP_F_main_BB__13_10 = 6'd10;
parameter [5:0] LEGUP_F_main_BB__13_11 = 6'd11;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_12 = 6'd12;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_13 = 6'd13;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_14 = 6'd14;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_15 = 6'd15;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_16 = 6'd16;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_17 = 6'd17;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_18 = 6'd18;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_19 = 6'd19;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_20 = 6'd20;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_21 = 6'd21;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_22 = 6'd22;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_23 = 6'd23;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_24 = 6'd24;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_25 = 6'd25;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_26 = 6'd26;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_27 = 6'd27;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_28 = 6'd28;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_29 = 6'd29;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_30 = 6'd30;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_31 = 6'd31;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_32 = 6'd32;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_33 = 6'd33;
parameter [5:0] LEGUP_F_main_BB_lrphipreheader_34 = 6'd34;
parameter [5:0] LEGUP_loop_pipeline_wait_loop5_1_35 = 6'd35;
parameter [5:0] LEGUP_F_main_BB__60_36 = 6'd36;
parameter [5:0] LEGUP_F_main_BB__62_37 = 6'd37;
parameter [5:0] LEGUP_F_main_BB__64_38 = 6'd38;
parameter [8:0] tag_offset = 9'd0;
parameter [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] tag_addr_offset = {tag_offset, 23'd0};

input  clk;
input  clk2x;
input  clk1x_follower;
input  reset;
input  start;
output reg  finish;
input  memory_controller_waitrequest;
output reg [31:0] return_val;
reg [5:0] cur_state;
reg [5:0] next_state;
reg [31:0] main_preheader2_1;
reg [31:0] main_preheader2_1_reg;
reg [31:0] main_preheader2_2;
reg [31:0] main_preheader2_2_reg;
reg [31:0] main_preheader2_3;
reg [31:0] main_preheader2_3_reg;
reg [31:0] main_preheader2_4;
reg [31:0] main_preheader2_4_reg;
reg [31:0] main_preheader2_5;
reg [31:0] main_preheader2_5_reg;
reg [31:0] main_preheader2_6;
reg [31:0] main_preheader2_6_reg;
reg [31:0] main_preheader2_7;
reg [31:0] main_preheader2_7_reg;
reg [31:0] main_preheader2_8;
reg [31:0] main_preheader2_8_reg;
reg [31:0] main_preheader2_9;
reg [31:0] main_preheader2_9_reg;
reg [31:0] main_preheader2_10;
reg [31:0] main_preheader2_10_reg;
reg [31:0] main_preheader2_11;
reg [31:0] main_preheader2_11_reg;
reg [31:0] main_preheader2_12;
reg [31:0] main_preheader2_12_reg;
reg [31:0] main_13_indvar4;
reg [31:0] main_13_indvar4_reg;
reg [31:0] main_13_i010;
reg [31:0] main_13_i010_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_13_scevgep6;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_13_scevgep6_reg;
reg [31:0] main_13_14;
reg [31:0] main_13_14_reg;
reg [31:0] main_13_15;
reg [31:0] main_13_15_reg;
reg [31:0] main_13_16;
reg [31:0] main_13_16_reg;
reg [31:0] main_13_indvarnext5;
reg [31:0] main_13_indvarnext5_reg;
reg  main_13_exitcond;
reg  main_13_exitcond_reg;
reg [31:0] main_lrphipreheader_17;
reg [31:0] main_lrphipreheader_17_reg;
reg [31:0] main_lrphipreheader_18;
reg [31:0] main_lrphipreheader_18_reg;
reg [31:0] main_lrphipreheader_19;
reg [31:0] main_lrphipreheader_19_reg;
reg [31:0] main_lrphipreheader_20;
reg [31:0] main_lrphipreheader_20_reg;
reg [31:0] main_lrphipreheader_21;
reg [31:0] main_lrphipreheader_21_reg;
reg [31:0] main_lrphipreheader_22;
reg [31:0] main_lrphipreheader_22_reg;
reg [31:0] main_lrphipreheader_23;
reg [31:0] main_lrphipreheader_23_reg;
reg [31:0] main_lrphipreheader_24;
reg [31:0] main_lrphipreheader_24_reg;
reg [31:0] main_lrphipreheader_25;
reg [31:0] main_lrphipreheader_25_reg;
reg [31:0] main_lrphipreheader_26;
reg [31:0] main_lrphipreheader_26_reg;
reg [31:0] main_lrphipreheader_27;
reg [31:0] main_lrphipreheader_27_reg;
reg [31:0] main_lrphipreheader_28;
reg [31:0] main_lrphipreheader_28_reg;
reg [31:0] main_lrphipreheader_29;
reg [31:0] main_lrphipreheader_29_reg;
reg [31:0] main_lrphipreheader_30;
reg [31:0] main_lrphipreheader_30_reg;
reg [31:0] main_lrphipreheader_31;
reg [31:0] main_lrphipreheader_31_reg;
reg [31:0] main_lrphipreheader_32;
reg [31:0] main_lrphipreheader_32_reg;
reg [31:0] main_lrphipreheader_33;
reg [31:0] main_lrphipreheader_33_reg;
reg [31:0] main_lrphipreheader_34;
reg [31:0] main_lrphipreheader_34_reg;
reg [31:0] main_lrphipreheader_35;
reg [31:0] main_lrphipreheader_35_reg;
reg [31:0] main_lrphipreheader_36;
reg [31:0] main_lrphipreheader_36_reg;
reg [31:0] main_lrphipreheader_37;
reg [31:0] main_lrphipreheader_37_reg;
reg [31:0] main_lrphipreheader_38;
reg [31:0] main_lrphipreheader_38_reg;
reg [31:0] main_lrphipreheader_39;
reg [31:0] main_lrphipreheader_39_reg;
reg [31:0] main_lrphipreheader_40;
reg [31:0] main_lrphipreheader_40_reg;
reg [31:0] main_lrphipreheader_41;
reg [31:0] main_lrphipreheader_41_reg;
reg [31:0] main_lrphipreheader_42;
reg [31:0] main_lrphipreheader_42_reg;
reg [31:0] main_lrphipreheader_43;
reg [31:0] main_lrphipreheader_43_reg;
reg [31:0] main_lrphipreheader_44;
reg [31:0] main_lrphipreheader_44_reg;
reg [31:0] main_lrphipreheader_45;
reg [31:0] main_lrphipreheader_45_reg;
reg [31:0] main_lrphipreheader_46;
reg [31:0] main_lrphipreheader_46_reg;
reg [31:0] main_lrphipreheader_47;
reg [31:0] main_lrphipreheader_47_reg;
reg [31:0] main_lrphipreheader_48;
reg [31:0] main_lrphipreheader_48_reg;
reg [31:0] main_lrphipreheader_49;
reg [31:0] main_lrphipreheader_49_reg;
reg [31:0] main_lrphipreheader_50;
reg [31:0] main_lrphipreheader_50_reg;
reg [31:0] main_lrphipreheader_51;
reg [31:0] main_lrphipreheader_51_reg;
reg  main_lrphipreheader_53;
reg  main_lrphipreheader_53_reg;
reg [31:0] main_54_indvar;
reg [31:0] main_54_indvar_reg;
reg [31:0] main_54_55;
reg [31:0] main_54_55_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_54_scevgep;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_54_scevgep_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_54_scevgep2;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_54_scevgep2_reg;
reg [31:0] main_54_56;
reg [31:0] main_54_56_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_54_scevgep3;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_54_scevgep3_reg;
reg [31:0] main_54_57;
reg [31:0] main_54_57_reg;
reg [31:0] main_54_58;
reg [31:0] main_54_58_reg;
reg [31:0] main_54_59;
reg [31:0] main_54_59_reg;
reg [31:0] main_54_indvarnext;
reg [31:0] main_54_indvarnext_reg;
reg  main_54_exitcond1;
reg  main_54_exitcond1_reg;
reg [6:0] array_address_a;
reg  array_write_enable_a;
reg [31:0] array_in_a;
wire [31:0] array_out_a;
reg [6:0] array_address_b;
reg  array_write_enable_b;
reg [31:0] array_in_b;
wire [31:0] array_out_b;
reg  loop5_1_pipeline_start;
reg  loop5_1_started;
reg [1:0] loop5_1_ii_state;
reg [31:0] loop5_1_i_stage0;
reg  loop5_1_epilogue;
reg  loop5_1_valid_bit_0;
reg  loop5_1_valid_bit_1;
reg  loop5_1_valid_bit_2;
reg  loop5_1_valid_bit_3;
reg  loop5_1_valid_bit_4;
reg  loop5_1_valid_bit_5;
reg  loop5_1_valid_bit_6;
reg [31:0] loop5_1_i_stage1;
reg [31:0] main_54_55_reg_stage1;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_54_scevgep_reg_stage1;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_54_scevgep2_reg_stage0;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_54_scevgep2_reg_stage1;
reg [31:0] main_54_56_reg_stage0;
reg [31:0] main_54_56_reg_stage1;
reg  loop5_1_pipeline_exit_cond;
reg  loop5_1_pipeline_finish;
reg  lpm_mult_main_13_15_en;
reg [31:0] main_13_15_stage0_reg;
reg  lpm_mult_main_54_59_en;
reg [31:0] main_54_59_stage0_reg;

// Local Rams


// @array = internal unnamed_addr global [100 x i32] zeroinitializer, align 4
ram_dual_port array (
	.clk( clk ),
	.clken( !memory_controller_waitrequest ),
	.address_a( array_address_a ),
	.address_b( array_address_b ),
	.wren_a( array_write_enable_a ),
	.wren_b( array_write_enable_b ),
	.data_a( array_in_a ),
	.data_b( array_in_b ),
	.byteena_a( 1'b1 ),
	.byteena_b( 1'b1 ),
	.q_a( array_out_a ),
	.q_b( array_out_b)
);
defparam array.width_a = 32;
defparam array.width_b = 32;
defparam array.widthad_a = 7;
defparam array.widthad_b = 7;
defparam array.width_be_a = 1;
defparam array.width_be_b = 1;
defparam array.numwords_a = 100;
defparam array.numwords_b = 100;
defparam array.latency = 1;
defparam array.init_file = "array.mif";


/* Unsynthesizable Statements */
always @(posedge clk)
	if (!memory_controller_waitrequest) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %52 = tail call i32 (i8*, ...)* @printf(i8* getelementptr inbounds ([12 x i8]* @.str6, i32 0, i32 0), i32 %51) #2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_34)) begin
		$write("Result: %d\n", $signed(main_lrphipreheader_51));
		// to fix quartus warning
		if (reset == 1'b0 && ^(main_lrphipreheader_51) === 1'bX) finish <= 0;
	end
	/* main: %60*/
	/*   %61 = tail call i32 (i8*, ...)* @printf(i8* getelementptr inbounds ([14 x i8]* @.str7, i32 0, i32 0)) #2*/
	if ((cur_state == LEGUP_F_main_BB__60_36)) begin
		$write("RESULT: PASS\n");
	end
	/* main: %62*/
	/*   %63 = tail call i32 (i8*, ...)* @printf(i8* getelementptr inbounds ([14 x i8]* @.str8, i32 0, i32 0)) #2*/
	if ((cur_state == LEGUP_F_main_BB__62_37)) begin
		$write("RESULT: FAIL\n");
	end
end
always @(posedge clk) begin
if (reset == 1'b1)
	cur_state <= LEGUP_0;
else if (memory_controller_waitrequest == 1'd1)
	cur_state <= cur_state;
else
	cur_state <= next_state;
end

always @(*)
begin
next_state = cur_state;
case(cur_state)  // synthesis parallel_case  
LEGUP_0:
	if ((start == 1'd1))
		next_state = LEGUP_F_main_BB__13_8;
LEGUP_F_main_BB__13_10:
		next_state = LEGUP_F_main_BB__13_11;
LEGUP_F_main_BB__13_11:
	if ((main_13_exitcond == 1'd1))
		next_state = LEGUP_F_main_BB_preheader2_1;
	else if ((main_13_exitcond == 1'd0))
		next_state = LEGUP_F_main_BB__13_8;
LEGUP_F_main_BB__13_8:
		next_state = LEGUP_F_main_BB__13_9;
LEGUP_F_main_BB__13_9:
		next_state = LEGUP_F_main_BB__13_10;
LEGUP_F_main_BB__60_36:
		next_state = LEGUP_F_main_BB__64_38;
LEGUP_F_main_BB__62_37:
		next_state = LEGUP_F_main_BB__64_38;
LEGUP_F_main_BB__64_38:
		next_state = LEGUP_0;
LEGUP_F_main_BB_lrphipreheader_12:
		next_state = LEGUP_F_main_BB_lrphipreheader_13;
LEGUP_F_main_BB_lrphipreheader_13:
		next_state = LEGUP_F_main_BB_lrphipreheader_14;
LEGUP_F_main_BB_lrphipreheader_14:
		next_state = LEGUP_F_main_BB_lrphipreheader_15;
LEGUP_F_main_BB_lrphipreheader_15:
		next_state = LEGUP_F_main_BB_lrphipreheader_16;
LEGUP_F_main_BB_lrphipreheader_16:
		next_state = LEGUP_F_main_BB_lrphipreheader_17;
LEGUP_F_main_BB_lrphipreheader_17:
		next_state = LEGUP_F_main_BB_lrphipreheader_18;
LEGUP_F_main_BB_lrphipreheader_18:
		next_state = LEGUP_F_main_BB_lrphipreheader_19;
LEGUP_F_main_BB_lrphipreheader_19:
		next_state = LEGUP_F_main_BB_lrphipreheader_20;
LEGUP_F_main_BB_lrphipreheader_20:
		next_state = LEGUP_F_main_BB_lrphipreheader_21;
LEGUP_F_main_BB_lrphipreheader_21:
		next_state = LEGUP_F_main_BB_lrphipreheader_22;
LEGUP_F_main_BB_lrphipreheader_22:
		next_state = LEGUP_F_main_BB_lrphipreheader_23;
LEGUP_F_main_BB_lrphipreheader_23:
		next_state = LEGUP_F_main_BB_lrphipreheader_24;
LEGUP_F_main_BB_lrphipreheader_24:
		next_state = LEGUP_F_main_BB_lrphipreheader_25;
LEGUP_F_main_BB_lrphipreheader_25:
		next_state = LEGUP_F_main_BB_lrphipreheader_26;
LEGUP_F_main_BB_lrphipreheader_26:
		next_state = LEGUP_F_main_BB_lrphipreheader_27;
LEGUP_F_main_BB_lrphipreheader_27:
		next_state = LEGUP_F_main_BB_lrphipreheader_28;
LEGUP_F_main_BB_lrphipreheader_28:
		next_state = LEGUP_F_main_BB_lrphipreheader_29;
LEGUP_F_main_BB_lrphipreheader_29:
		next_state = LEGUP_F_main_BB_lrphipreheader_30;
LEGUP_F_main_BB_lrphipreheader_30:
		next_state = LEGUP_F_main_BB_lrphipreheader_31;
LEGUP_F_main_BB_lrphipreheader_31:
		next_state = LEGUP_F_main_BB_lrphipreheader_32;
LEGUP_F_main_BB_lrphipreheader_32:
		next_state = LEGUP_F_main_BB_lrphipreheader_33;
LEGUP_F_main_BB_lrphipreheader_33:
		next_state = LEGUP_F_main_BB_lrphipreheader_34;
LEGUP_F_main_BB_lrphipreheader_34:
	if ((main_lrphipreheader_53 == 1'd1))
		next_state = LEGUP_F_main_BB__60_36;
	else if ((main_lrphipreheader_53 == 1'd0))
		next_state = LEGUP_F_main_BB__62_37;
LEGUP_F_main_BB_preheader2_1:
		next_state = LEGUP_F_main_BB_preheader2_2;
LEGUP_F_main_BB_preheader2_2:
		next_state = LEGUP_F_main_BB_preheader2_3;
LEGUP_F_main_BB_preheader2_3:
		next_state = LEGUP_F_main_BB_preheader2_4;
LEGUP_F_main_BB_preheader2_4:
		next_state = LEGUP_F_main_BB_preheader2_5;
LEGUP_F_main_BB_preheader2_5:
		next_state = LEGUP_F_main_BB_preheader2_6;
LEGUP_F_main_BB_preheader2_6:
		next_state = LEGUP_F_main_BB_preheader2_7;
LEGUP_F_main_BB_preheader2_7:
		next_state = LEGUP_loop_pipeline_wait_loop5_1_35;
LEGUP_loop_pipeline_wait_loop5_1_35:
	if ((loop5_1_pipeline_finish == 1'd1))
		next_state = LEGUP_F_main_BB_lrphipreheader_12;
	else if ((loop5_1_pipeline_finish == 1'd1))
		next_state = LEGUP_F_main_BB_lrphipreheader_12;
default:
	next_state = cur_state;
endcase

end
always @(*) begin
	/* main: %.preheader2*/
	/*   %1 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 0), align 4, !tbaa !2*/
		main_preheader2_1 = array_out_a;
end
always @(posedge clk) begin
	/* main: %.preheader2*/
	/*   %1 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 0), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_2)) begin
		main_preheader2_1_reg <= main_preheader2_1;
		if (start == 1'b0 && ^(main_preheader2_1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader2_1_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader2*/
	/*   %2 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 1), align 4, !tbaa !2*/
		main_preheader2_2 = array_out_b;
end
always @(posedge clk) begin
	/* main: %.preheader2*/
	/*   %2 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 1), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_2)) begin
		main_preheader2_2_reg <= main_preheader2_2;
		if (start == 1'b0 && ^(main_preheader2_2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader2_2_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader2*/
	/*   %3 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
		main_preheader2_3 = array_out_a;
end
always @(posedge clk) begin
	/* main: %.preheader2*/
	/*   %3 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_3)) begin
		main_preheader2_3_reg <= main_preheader2_3;
		if (start == 1'b0 && ^(main_preheader2_3) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader2_3_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader2*/
	/*   %4 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
		main_preheader2_4 = array_out_b;
end
always @(posedge clk) begin
	/* main: %.preheader2*/
	/*   %4 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_3)) begin
		main_preheader2_4_reg <= main_preheader2_4;
		if (start == 1'b0 && ^(main_preheader2_4) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader2_4_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader2*/
	/*   %5 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 3), align 4, !tbaa !2*/
		main_preheader2_5 = array_out_a;
end
always @(posedge clk) begin
	/* main: %.preheader2*/
	/*   %5 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 3), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_4)) begin
		main_preheader2_5_reg <= main_preheader2_5;
		if (start == 1'b0 && ^(main_preheader2_5) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader2_5_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader2*/
	/*   %6 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
		main_preheader2_6 = array_out_b;
end
always @(posedge clk) begin
	/* main: %.preheader2*/
	/*   %6 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_4)) begin
		main_preheader2_6_reg <= main_preheader2_6;
		if (start == 1'b0 && ^(main_preheader2_6) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader2_6_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader2*/
	/*   %7 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
		main_preheader2_7 = array_out_a;
end
always @(posedge clk) begin
	/* main: %.preheader2*/
	/*   %7 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_5)) begin
		main_preheader2_7_reg <= main_preheader2_7;
		if (start == 1'b0 && ^(main_preheader2_7) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader2_7_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader2*/
	/*   %8 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 3), align 4, !tbaa !2*/
		main_preheader2_8 = array_out_b;
end
always @(posedge clk) begin
	/* main: %.preheader2*/
	/*   %8 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 3), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_5)) begin
		main_preheader2_8_reg <= main_preheader2_8;
		if (start == 1'b0 && ^(main_preheader2_8) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader2_8_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader2*/
	/*   %9 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
		main_preheader2_9 = array_out_a;
end
always @(posedge clk) begin
	/* main: %.preheader2*/
	/*   %9 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_6)) begin
		main_preheader2_9_reg <= main_preheader2_9;
		if (start == 1'b0 && ^(main_preheader2_9) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader2_9_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader2*/
	/*   %10 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
		main_preheader2_10 = array_out_b;
end
always @(posedge clk) begin
	/* main: %.preheader2*/
	/*   %10 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_6)) begin
		main_preheader2_10_reg <= main_preheader2_10;
		if (start == 1'b0 && ^(main_preheader2_10) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader2_10_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader2*/
	/*   %11 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 5), align 4, !tbaa !2*/
		main_preheader2_11 = array_out_a;
end
always @(posedge clk) begin
	/* main: %.preheader2*/
	/*   %11 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 5), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_7)) begin
		main_preheader2_11_reg <= main_preheader2_11;
		if (start == 1'b0 && ^(main_preheader2_11) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader2_11_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.preheader2*/
	/*   %12 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 6), align 4, !tbaa !2*/
		main_preheader2_12 = array_out_b;
end
always @(posedge clk) begin
	/* main: %.preheader2*/
	/*   %12 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 6), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_7)) begin
		main_preheader2_12_reg <= main_preheader2_12;
		if (start == 1'b0 && ^(main_preheader2_12) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_preheader2_12_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %13*/
	/*   %indvar4 = phi i32 [ %indvar.next5, %13 ], [ 0, %0 ]*/
	if ((((cur_state == LEGUP_0) & (memory_controller_waitrequest == 1'd0)) & (start == 1'd1))) begin
		main_13_indvar4 = 32'd0;
	end
	/* main: %13*/
	/*   %indvar4 = phi i32 [ %indvar.next5, %13 ], [ 0, %0 ]*/
	else /* if ((((cur_state == LEGUP_F_main_BB__13_11) & (memory_controller_waitrequest == 1'd0)) & (main_13_exitcond == 1'd0))) */ begin
		main_13_indvar4 = main_13_indvarnext5;
	end
end
always @(posedge clk) begin
	/* main: %13*/
	/*   %indvar4 = phi i32 [ %indvar.next5, %13 ], [ 0, %0 ]*/
	if ((((cur_state == LEGUP_0) & (memory_controller_waitrequest == 1'd0)) & (start == 1'd1))) begin
		main_13_indvar4_reg <= main_13_indvar4;
		if (start == 1'b0 && ^(main_13_indvar4) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_13_indvar4_reg"); $finish; end
	end
	/* main: %13*/
	/*   %indvar4 = phi i32 [ %indvar.next5, %13 ], [ 0, %0 ]*/
	if ((((cur_state == LEGUP_F_main_BB__13_11) & (memory_controller_waitrequest == 1'd0)) & (main_13_exitcond == 1'd0))) begin
		main_13_indvar4_reg <= main_13_indvar4;
		if (start == 1'b0 && ^(main_13_indvar4) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_13_indvar4_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %13*/
	/*   %i.010 = add i32 %indvar4, 1*/
		main_13_i010 = (main_13_indvar4_reg + 32'd1);
end
always @(posedge clk) begin
	/* main: %13*/
	/*   %i.010 = add i32 %indvar4, 1*/
	if ((cur_state == LEGUP_F_main_BB__13_8)) begin
		main_13_i010_reg <= main_13_i010;
		if (start == 1'b0 && ^(main_13_i010) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_13_i010_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %13*/
	/*   %scevgep6 = getelementptr [100 x i32]* @array, i32 0, i32 %i.010*/
		main_13_scevgep6 = (1'd0 + (4 * main_13_i010_reg));
end
always @(posedge clk) begin
	/* main: %13*/
	/*   %scevgep6 = getelementptr [100 x i32]* @array, i32 0, i32 %i.010*/
	if ((cur_state == LEGUP_F_main_BB__13_9)) begin
		main_13_scevgep6_reg <= main_13_scevgep6;
		if (start == 1'b0 && ^(main_13_scevgep6) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_13_scevgep6_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %13*/
	/*   %14 = add i32 %indvar4, 4*/
		main_13_14 = (main_13_indvar4_reg + 32'd4);
end
always @(posedge clk) begin
	/* main: %13*/
	/*   %14 = add i32 %indvar4, 4*/
	if ((cur_state == LEGUP_F_main_BB__13_9)) begin
		main_13_14_reg <= main_13_14;
		if (start == 1'b0 && ^(main_13_14) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_13_14_reg"); $finish; end
	end
end
always @(*) begin
	main_13_15 = main_13_15_stage0_reg;
end
always @(posedge clk) begin
	/* main: %13*/
	/*   %15 = mul nsw i32 %14, %i.010*/
	if ((cur_state == LEGUP_F_main_BB__13_10)) begin
		main_13_15_reg <= main_13_15;
		if (start == 1'b0 && ^(main_13_15) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_13_15_reg"); $finish; end
	end
	/* main: %13*/
	/*   %15 = mul nsw i32 %14, %i.010*/
	if ((cur_state == LEGUP_F_main_BB__13_10)) begin
		main_13_15_reg <= main_13_15;
		if (start == 1'b0 && ^(main_13_15) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_13_15_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %13*/
	/*   %16 = add nsw i32 %15, -19*/
		main_13_16 = (main_13_15 + -32'd19);
end
always @(posedge clk) begin
	/* main: %13*/
	/*   %16 = add nsw i32 %15, -19*/
	if ((cur_state == LEGUP_F_main_BB__13_10)) begin
		main_13_16_reg <= main_13_16;
		if (start == 1'b0 && ^(main_13_16) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_13_16_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %13*/
	/*   %indvar.next5 = add i32 %indvar4, 1*/
		main_13_indvarnext5 = (main_13_indvar4_reg + 32'd1);
end
always @(posedge clk) begin
	/* main: %13*/
	/*   %indvar.next5 = add i32 %indvar4, 1*/
	if ((cur_state == LEGUP_F_main_BB__13_11)) begin
		main_13_indvarnext5_reg <= main_13_indvarnext5;
		if (start == 1'b0 && ^(main_13_indvarnext5) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_13_indvarnext5_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %13*/
	/*   %exitcond = icmp eq i32 %indvar.next5, 99*/
		main_13_exitcond = (main_13_indvarnext5 == 32'd99);
end
always @(posedge clk) begin
	/* main: %13*/
	/*   %exitcond = icmp eq i32 %indvar.next5, 99*/
	if ((cur_state == LEGUP_F_main_BB__13_11)) begin
		main_13_exitcond_reg <= main_13_exitcond;
		if (start == 1'b0 && ^(main_13_exitcond) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_13_exitcond_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %17 = add nsw i32 %2, %1*/
		main_lrphipreheader_17 = (main_preheader2_2_reg + main_preheader2_1_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %17 = add nsw i32 %2, %1*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_12)) begin
		main_lrphipreheader_17_reg <= main_lrphipreheader_17;
		if (start == 1'b0 && ^(main_lrphipreheader_17) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_17_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %18 = add nsw i32 %3, %17*/
		main_lrphipreheader_18 = (main_preheader2_3_reg + main_lrphipreheader_17_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %18 = add nsw i32 %3, %17*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_14)) begin
		main_lrphipreheader_18_reg <= main_lrphipreheader_18;
		if (start == 1'b0 && ^(main_lrphipreheader_18) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_18_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %19 = add nsw i32 %4, %18*/
		main_lrphipreheader_19 = (main_preheader2_4_reg + main_lrphipreheader_18_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %19 = add nsw i32 %4, %18*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_15)) begin
		main_lrphipreheader_19_reg <= main_lrphipreheader_19;
		if (start == 1'b0 && ^(main_lrphipreheader_19) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_19_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %20 = add nsw i32 %5, %19*/
		main_lrphipreheader_20 = (main_preheader2_5_reg + main_lrphipreheader_19_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %20 = add nsw i32 %5, %19*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_16)) begin
		main_lrphipreheader_20_reg <= main_lrphipreheader_20;
		if (start == 1'b0 && ^(main_lrphipreheader_20) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_20_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %21 = add nsw i32 %6, %20*/
		main_lrphipreheader_21 = (main_preheader2_6_reg + main_lrphipreheader_20_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %21 = add nsw i32 %6, %20*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_17)) begin
		main_lrphipreheader_21_reg <= main_lrphipreheader_21;
		if (start == 1'b0 && ^(main_lrphipreheader_21) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_21_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %22 = add nsw i32 %7, %21*/
		main_lrphipreheader_22 = (main_preheader2_7_reg + main_lrphipreheader_21_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %22 = add nsw i32 %7, %21*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_22)) begin
		main_lrphipreheader_22_reg <= main_lrphipreheader_22;
		if (start == 1'b0 && ^(main_lrphipreheader_22) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_22_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %23 = add nsw i32 %8, %22*/
		main_lrphipreheader_23 = (main_preheader2_8_reg + main_lrphipreheader_22_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %23 = add nsw i32 %8, %22*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_23)) begin
		main_lrphipreheader_23_reg <= main_lrphipreheader_23;
		if (start == 1'b0 && ^(main_lrphipreheader_23) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_23_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %24 = add nsw i32 %9, %23*/
		main_lrphipreheader_24 = (main_preheader2_9_reg + main_lrphipreheader_23_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %24 = add nsw i32 %9, %23*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_24)) begin
		main_lrphipreheader_24_reg <= main_lrphipreheader_24;
		if (start == 1'b0 && ^(main_lrphipreheader_24) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_24_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %25 = add nsw i32 %10, %24*/
		main_lrphipreheader_25 = (main_preheader2_10_reg + main_lrphipreheader_24_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %25 = add nsw i32 %10, %24*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_25)) begin
		main_lrphipreheader_25_reg <= main_lrphipreheader_25;
		if (start == 1'b0 && ^(main_lrphipreheader_25) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_25_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %26 = add nsw i32 %11, %25*/
		main_lrphipreheader_26 = (main_preheader2_11_reg + main_lrphipreheader_25_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %26 = add nsw i32 %11, %25*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_30)) begin
		main_lrphipreheader_26_reg <= main_lrphipreheader_26;
		if (start == 1'b0 && ^(main_lrphipreheader_26) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_26_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %27 = add nsw i32 %12, %26*/
		main_lrphipreheader_27 = (main_preheader2_12_reg + main_lrphipreheader_26_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %27 = add nsw i32 %12, %26*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_31)) begin
		main_lrphipreheader_27_reg <= main_lrphipreheader_27;
		if (start == 1'b0 && ^(main_lrphipreheader_27) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_27_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %28 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 0), align 4, !tbaa !2*/
		main_lrphipreheader_28 = array_out_a;
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %28 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 0), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_13)) begin
		main_lrphipreheader_28_reg <= main_lrphipreheader_28;
		if (start == 1'b0 && ^(main_lrphipreheader_28) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_28_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %29 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 1), align 4, !tbaa !2*/
		main_lrphipreheader_29 = array_out_b;
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %29 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 1), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_13)) begin
		main_lrphipreheader_29_reg <= main_lrphipreheader_29;
		if (start == 1'b0 && ^(main_lrphipreheader_29) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_29_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %30 = add nsw i32 %29, %28*/
		main_lrphipreheader_30 = (main_lrphipreheader_29 + main_lrphipreheader_28);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %30 = add nsw i32 %29, %28*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_13)) begin
		main_lrphipreheader_30_reg <= main_lrphipreheader_30;
		if (start == 1'b0 && ^(main_lrphipreheader_30) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_30_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %31 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
		main_lrphipreheader_31 = array_out_a;
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %31 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_14)) begin
		main_lrphipreheader_31_reg <= main_lrphipreheader_31;
		if (start == 1'b0 && ^(main_lrphipreheader_31) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_31_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %32 = add nsw i32 %31, %30*/
		main_lrphipreheader_32 = (main_lrphipreheader_31_reg + main_lrphipreheader_30_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %32 = add nsw i32 %31, %30*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_18)) begin
		main_lrphipreheader_32_reg <= main_lrphipreheader_32;
		if (start == 1'b0 && ^(main_lrphipreheader_32) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_32_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %33 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 3), align 4, !tbaa !2*/
		main_lrphipreheader_33 = array_out_b;
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %33 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 3), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_14)) begin
		main_lrphipreheader_33_reg <= main_lrphipreheader_33;
		if (start == 1'b0 && ^(main_lrphipreheader_33) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_33_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %34 = add nsw i32 %33, %32*/
		main_lrphipreheader_34 = (main_lrphipreheader_33_reg + main_lrphipreheader_32_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %34 = add nsw i32 %33, %32*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_19)) begin
		main_lrphipreheader_34_reg <= main_lrphipreheader_34;
		if (start == 1'b0 && ^(main_lrphipreheader_34) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_34_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %35 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
		main_lrphipreheader_35 = array_out_a;
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %35 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_15)) begin
		main_lrphipreheader_35_reg <= main_lrphipreheader_35;
		if (start == 1'b0 && ^(main_lrphipreheader_35) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_35_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %36 = add nsw i32 %35, %34*/
		main_lrphipreheader_36 = (main_lrphipreheader_35_reg + main_lrphipreheader_34_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %36 = add nsw i32 %35, %34*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_20)) begin
		main_lrphipreheader_36_reg <= main_lrphipreheader_36;
		if (start == 1'b0 && ^(main_lrphipreheader_36) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_36_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %37 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 5), align 4, !tbaa !2*/
		main_lrphipreheader_37 = array_out_b;
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %37 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 5), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_15)) begin
		main_lrphipreheader_37_reg <= main_lrphipreheader_37;
		if (start == 1'b0 && ^(main_lrphipreheader_37) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_37_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %38 = add nsw i32 %37, %36*/
		main_lrphipreheader_38 = (main_lrphipreheader_37_reg + main_lrphipreheader_36_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %38 = add nsw i32 %37, %36*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_21)) begin
		main_lrphipreheader_38_reg <= main_lrphipreheader_38;
		if (start == 1'b0 && ^(main_lrphipreheader_38) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_38_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %39 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 6), align 4, !tbaa !2*/
		main_lrphipreheader_39 = array_out_a;
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %39 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 6), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_16)) begin
		main_lrphipreheader_39_reg <= main_lrphipreheader_39;
		if (start == 1'b0 && ^(main_lrphipreheader_39) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_39_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %40 = add nsw i32 %39, %38*/
		main_lrphipreheader_40 = (main_lrphipreheader_39_reg + main_lrphipreheader_38_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %40 = add nsw i32 %39, %38*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_26)) begin
		main_lrphipreheader_40_reg <= main_lrphipreheader_40;
		if (start == 1'b0 && ^(main_lrphipreheader_40) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_40_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %41 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 7), align 4, !tbaa !2*/
		main_lrphipreheader_41 = array_out_b;
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %41 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 7), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_16)) begin
		main_lrphipreheader_41_reg <= main_lrphipreheader_41;
		if (start == 1'b0 && ^(main_lrphipreheader_41) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_41_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %42 = add nsw i32 %41, %40*/
		main_lrphipreheader_42 = (main_lrphipreheader_41_reg + main_lrphipreheader_40_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %42 = add nsw i32 %41, %40*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_27)) begin
		main_lrphipreheader_42_reg <= main_lrphipreheader_42;
		if (start == 1'b0 && ^(main_lrphipreheader_42) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_42_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %43 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 8), align 4, !tbaa !2*/
		main_lrphipreheader_43 = array_out_a;
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %43 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 8), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_17)) begin
		main_lrphipreheader_43_reg <= main_lrphipreheader_43;
		if (start == 1'b0 && ^(main_lrphipreheader_43) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_43_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %44 = add nsw i32 %43, %42*/
		main_lrphipreheader_44 = (main_lrphipreheader_43_reg + main_lrphipreheader_42_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %44 = add nsw i32 %43, %42*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_28)) begin
		main_lrphipreheader_44_reg <= main_lrphipreheader_44;
		if (start == 1'b0 && ^(main_lrphipreheader_44) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_44_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %45 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 9), align 4, !tbaa !2*/
		main_lrphipreheader_45 = array_out_b;
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %45 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 9), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_17)) begin
		main_lrphipreheader_45_reg <= main_lrphipreheader_45;
		if (start == 1'b0 && ^(main_lrphipreheader_45) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_45_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %46 = add nsw i32 %45, %44*/
		main_lrphipreheader_46 = (main_lrphipreheader_45_reg + main_lrphipreheader_44_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %46 = add nsw i32 %45, %44*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_29)) begin
		main_lrphipreheader_46_reg <= main_lrphipreheader_46;
		if (start == 1'b0 && ^(main_lrphipreheader_46) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_46_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %47 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 10), align 4, !tbaa !2*/
		main_lrphipreheader_47 = array_out_a;
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %47 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 10), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_18)) begin
		main_lrphipreheader_47_reg <= main_lrphipreheader_47;
		if (start == 1'b0 && ^(main_lrphipreheader_47) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_47_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %48 = add nsw i32 %47, %46*/
		main_lrphipreheader_48 = (main_lrphipreheader_47_reg + main_lrphipreheader_46_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %48 = add nsw i32 %47, %46*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_32)) begin
		main_lrphipreheader_48_reg <= main_lrphipreheader_48;
		if (start == 1'b0 && ^(main_lrphipreheader_48) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_48_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %49 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 11), align 4, !tbaa !2*/
		main_lrphipreheader_49 = array_out_b;
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %49 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 11), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_18)) begin
		main_lrphipreheader_49_reg <= main_lrphipreheader_49;
		if (start == 1'b0 && ^(main_lrphipreheader_49) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_49_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %50 = add nsw i32 %49, %48*/
		main_lrphipreheader_50 = (main_lrphipreheader_49_reg + main_lrphipreheader_48_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %50 = add nsw i32 %49, %48*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_33)) begin
		main_lrphipreheader_50_reg <= main_lrphipreheader_50;
		if (start == 1'b0 && ^(main_lrphipreheader_50) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_50_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %51 = add nsw i32 %50, %27*/
		main_lrphipreheader_51 = (main_lrphipreheader_50_reg + main_lrphipreheader_27_reg);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %51 = add nsw i32 %50, %27*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_34)) begin
		main_lrphipreheader_51_reg <= main_lrphipreheader_51;
		if (start == 1'b0 && ^(main_lrphipreheader_51) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_51_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %53 = icmp eq i32 %51, 39*/
		main_lrphipreheader_53 = (main_lrphipreheader_51 == 32'd39);
end
always @(posedge clk) begin
	/* main: %.lr.ph.i.preheader*/
	/*   %53 = icmp eq i32 %51, 39*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_34)) begin
		main_lrphipreheader_53_reg <= main_lrphipreheader_53;
		if (start == 1'b0 && ^(main_lrphipreheader_53) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_lrphipreheader_53_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %54*/
	/*   %indvar = phi i32 [ %indvar.next, %54 ], [ 0, %.preheader2 ], !legup.canonical_induction !6, !legup.pipeline.start_time !7, !legup.pipeline.avail_time !7, !legup.pipeline.stage !7
	start_time: 0 avail_time: 0 stage: 0 II: 3 start_ii_state = 0 % 3 = 0 avail_ii_state = 0 % 3 = 0*/
if (reset) begin main_54_indvar = 0; end
		main_54_indvar = 32'd0;
end
always @(posedge clk) begin
	/* main: %54*/
	/*   %indvar = phi i32 [ %indvar.next, %54 ], [ 0, %.preheader2 ], !legup.canonical_induction !6, !legup.pipeline.start_time !7, !legup.pipeline.avail_time !7, !legup.pipeline.stage !7
	start_time: 0 avail_time: 0 stage: 0 II: 3 start_ii_state = 0 % 3 = 0 avail_ii_state = 0 % 3 = 0*/
	if (((cur_state == LEGUP_F_main_BB_preheader2_7) & (memory_controller_waitrequest == 1'd0))) begin
		main_54_indvar_reg <= main_54_indvar;
		if (start == 1'b0 && ^(main_54_indvar) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_indvar_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %54*/
	/*   %55 = add i32 %indvar, 1, !legup.pipeline.start_time !8, !legup.pipeline.avail_time !8, !legup.pipeline.stage !7
	start_time: 2 avail_time: 2 stage: 0 II: 3 start_ii_state = 2 % 3 = 2 avail_ii_state = 2 % 3 = 2*/
		main_54_55 = (loop5_1_i_stage0 + 32'd1);
end
always @(posedge clk) begin
	/* main: %54*/
	/*   %55 = add i32 %indvar, 1, !legup.pipeline.start_time !8, !legup.pipeline.avail_time !8, !legup.pipeline.stage !7
	start_time: 2 avail_time: 2 stage: 0 II: 3 start_ii_state = 2 % 3 = 2 avail_ii_state = 2 % 3 = 2*/
	if ((~(memory_controller_waitrequest) & ((loop5_1_ii_state == 2'd2) & loop5_1_valid_bit_2))) begin
		main_54_55_reg <= main_54_55;
		if (start == 1'b0 && ^(main_54_55) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_55_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %54*/
	/*   %scevgep = getelementptr [100 x i32]* @array, i32 0, i32 %55, !legup.pipeline.start_time !9, !legup.pipeline.avail_time !9, !legup.pipeline.stage !6
	start_time: 3 avail_time: 3 stage: 1 II: 3 start_ii_state = 3 % 3 = 0 avail_ii_state = 3 % 3 = 0*/
		main_54_scevgep = (1'd0 + (4 * main_54_55_reg_stage1));
end
always @(posedge clk) begin
	/* main: %54*/
	/*   %scevgep = getelementptr [100 x i32]* @array, i32 0, i32 %55, !legup.pipeline.start_time !9, !legup.pipeline.avail_time !9, !legup.pipeline.stage !6
	start_time: 3 avail_time: 3 stage: 1 II: 3 start_ii_state = 3 % 3 = 0 avail_ii_state = 3 % 3 = 0*/
	if ((~(memory_controller_waitrequest) & ((loop5_1_ii_state == 2'd0) & loop5_1_valid_bit_3))) begin
		main_54_scevgep_reg <= main_54_scevgep;
		if (start == 1'b0 && ^(main_54_scevgep) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_scevgep_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %54*/
	/*   %scevgep2 = getelementptr [100 x i32]* @array, i32 0, i32 %indvar, !legup.pipeline.start_time !7, !legup.pipeline.avail_time !7, !legup.pipeline.stage !7
	start_time: 0 avail_time: 0 stage: 0 II: 3 start_ii_state = 0 % 3 = 0 avail_ii_state = 0 % 3 = 0*/
		main_54_scevgep2 = (1'd0 + (4 * loop5_1_i_stage0));
end
always @(posedge clk) begin
	/* main: %54*/
	/*   %scevgep2 = getelementptr [100 x i32]* @array, i32 0, i32 %indvar, !legup.pipeline.start_time !7, !legup.pipeline.avail_time !7, !legup.pipeline.stage !7
	start_time: 0 avail_time: 0 stage: 0 II: 3 start_ii_state = 0 % 3 = 0 avail_ii_state = 0 % 3 = 0*/
	if ((~(memory_controller_waitrequest) & ((loop5_1_ii_state == 2'd0) & loop5_1_valid_bit_0))) begin
		main_54_scevgep2_reg <= main_54_scevgep2;
		if (start == 1'b0 && ^(main_54_scevgep2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_scevgep2_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %54*/
	/*   %56 = add i32 %indvar, 2, !legup.pipeline.start_time !6, !legup.pipeline.avail_time !6, !legup.pipeline.stage !7
	start_time: 1 avail_time: 1 stage: 0 II: 3 start_ii_state = 1 % 3 = 1 avail_ii_state = 1 % 3 = 1*/
		main_54_56 = (loop5_1_i_stage0 + 32'd2);
end
always @(posedge clk) begin
	/* main: %54*/
	/*   %56 = add i32 %indvar, 2, !legup.pipeline.start_time !6, !legup.pipeline.avail_time !6, !legup.pipeline.stage !7
	start_time: 1 avail_time: 1 stage: 0 II: 3 start_ii_state = 1 % 3 = 1 avail_ii_state = 1 % 3 = 1*/
	if ((~(memory_controller_waitrequest) & ((loop5_1_ii_state == 2'd1) & loop5_1_valid_bit_1))) begin
		main_54_56_reg <= main_54_56;
		if (start == 1'b0 && ^(main_54_56) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_56_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %54*/
	/*   %scevgep3 = getelementptr [100 x i32]* @array, i32 0, i32 %56, !legup.pipeline.start_time !9, !legup.pipeline.avail_time !9, !legup.pipeline.stage !6
	start_time: 3 avail_time: 3 stage: 1 II: 3 start_ii_state = 3 % 3 = 0 avail_ii_state = 3 % 3 = 0*/
		main_54_scevgep3 = (1'd0 + (4 * main_54_56_reg_stage1));
end
always @(posedge clk) begin
	/* main: %54*/
	/*   %scevgep3 = getelementptr [100 x i32]* @array, i32 0, i32 %56, !legup.pipeline.start_time !9, !legup.pipeline.avail_time !9, !legup.pipeline.stage !6
	start_time: 3 avail_time: 3 stage: 1 II: 3 start_ii_state = 3 % 3 = 0 avail_ii_state = 3 % 3 = 0*/
	if ((~(memory_controller_waitrequest) & ((loop5_1_ii_state == 2'd0) & loop5_1_valid_bit_3))) begin
		main_54_scevgep3_reg <= main_54_scevgep3;
		if (start == 1'b0 && ^(main_54_scevgep3) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_scevgep3_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %54*/
	/*   %57 = load i32* %scevgep3, align 4, !tbaa !2, !legup.pipeline.start_time !9, !legup.pipeline.avail_time !10, !legup.pipeline.stage !6
	start_time: 3 avail_time: 4 stage: 1 II: 3 start_ii_state = 3 % 3 = 0 avail_ii_state = 4 % 3 = 1*/
		main_54_57 = array_out_a;
end
always @(posedge clk) begin
	/* main: %54*/
	/*   %57 = load i32* %scevgep3, align 4, !tbaa !2, !legup.pipeline.start_time !9, !legup.pipeline.avail_time !10, !legup.pipeline.stage !6
	start_time: 3 avail_time: 4 stage: 1 II: 3 start_ii_state = 3 % 3 = 0 avail_ii_state = 4 % 3 = 1*/
	if ((~(memory_controller_waitrequest) & ((loop5_1_ii_state == 2'd1) & loop5_1_valid_bit_4))) begin
		main_54_57_reg <= main_54_57;
		if (start == 1'b0 && ^(main_54_57) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_57_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %54*/
	/*   %58 = load i32* %scevgep2, align 4, !tbaa !2, !legup.pipeline.start_time !9, !legup.pipeline.avail_time !10, !legup.pipeline.stage !6
	start_time: 3 avail_time: 4 stage: 1 II: 3 start_ii_state = 3 % 3 = 0 avail_ii_state = 4 % 3 = 1*/
		main_54_58 = array_out_b;
end
always @(posedge clk) begin
	/* main: %54*/
	/*   %58 = load i32* %scevgep2, align 4, !tbaa !2, !legup.pipeline.start_time !9, !legup.pipeline.avail_time !10, !legup.pipeline.stage !6
	start_time: 3 avail_time: 4 stage: 1 II: 3 start_ii_state = 3 % 3 = 0 avail_ii_state = 4 % 3 = 1*/
	if ((~(memory_controller_waitrequest) & ((loop5_1_ii_state == 2'd1) & loop5_1_valid_bit_4))) begin
		main_54_58_reg <= main_54_58;
		if (start == 1'b0 && ^(main_54_58) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_58_reg"); $finish; end
	end
end
always @(*) begin
	main_54_59 = main_54_59_stage0_reg;
end
always @(posedge clk) begin
	/* main: %54*/
	/*   %59 = mul nsw i32 %58, %57, !legup.pipeline.start_time !10, !legup.pipeline.avail_time !11, !legup.pipeline.stage !6
	start_time: 4 avail_time: 5 stage: 1 II: 3 start_ii_state = 4 % 3 = 1 avail_ii_state = 5 % 3 = 2*/
	if ((~(memory_controller_waitrequest) & ((loop5_1_ii_state == 2'd2) & loop5_1_valid_bit_5))) begin
		main_54_59_reg <= main_54_59;
		if (start == 1'b0 && ^(main_54_59) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_59_reg"); $finish; end
	end
	/* main: %54*/
	/*   %59 = mul nsw i32 %58, %57, !legup.pipeline.start_time !10, !legup.pipeline.avail_time !11, !legup.pipeline.stage !6
	start_time: 4 avail_time: 5 stage: 1 II: 3 start_ii_state = 4 % 3 = 1 avail_ii_state = 5 % 3 = 2*/
	if ((~(memory_controller_waitrequest) & ((loop5_1_ii_state == 2'd2) & loop5_1_valid_bit_5))) begin
		main_54_59_reg <= main_54_59;
		if (start == 1'b0 && ^(main_54_59) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_59_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %54*/
	/*   %indvar.next = add i32 %indvar, 1, !legup.pipeline.start_time !7, !legup.pipeline.avail_time !7, !legup.pipeline.stage !7
	start_time: 0 avail_time: 0 stage: 0 II: 3 start_ii_state = 0 % 3 = 0 avail_ii_state = 0 % 3 = 0*/
		main_54_indvarnext = (loop5_1_i_stage0 + 32'd1);
end
always @(posedge clk) begin
	/* main: %54*/
	/*   %indvar.next = add i32 %indvar, 1, !legup.pipeline.start_time !7, !legup.pipeline.avail_time !7, !legup.pipeline.stage !7
	start_time: 0 avail_time: 0 stage: 0 II: 3 start_ii_state = 0 % 3 = 0 avail_ii_state = 0 % 3 = 0*/
	if ((~(memory_controller_waitrequest) & ((loop5_1_ii_state == 2'd0) & loop5_1_valid_bit_0))) begin
		main_54_indvarnext_reg <= main_54_indvarnext;
		if (start == 1'b0 && ^(main_54_indvarnext) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_indvarnext_reg"); $finish; end
	end
end
always @(*) begin
		main_54_exitcond1 = loop5_1_pipeline_finish;
end
always @(posedge clk) begin
	if ((cur_state == LEGUP_loop_pipeline_wait_loop5_1_35)) begin
		main_54_exitcond1_reg <= loop5_1_pipeline_finish;
		if (start == 1'b0 && ^(loop5_1_pipeline_finish) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_exitcond1_reg"); $finish; end
	end
end
always @(*) begin
	array_address_a = 1'd0;
	/* main: %.preheader2*/
	/*   %1 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 0), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_1)) begin
		array_address_a = (1'd0 >>> 3'd2);
	end
	/* main: %.preheader2*/
	/*   %3 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_2)) begin
		array_address_a = ((1'd0 + (4 * 32'd2)) >>> 3'd2);
	end
	/* main: %.preheader2*/
	/*   %5 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 3), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_3)) begin
		array_address_a = ((1'd0 + (4 * 32'd3)) >>> 3'd2);
	end
	/* main: %.preheader2*/
	/*   %7 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_4)) begin
		array_address_a = ((1'd0 + (4 * 32'd2)) >>> 3'd2);
	end
	/* main: %.preheader2*/
	/*   %9 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_5)) begin
		array_address_a = ((1'd0 + (4 * 32'd4)) >>> 3'd2);
	end
	/* main: %.preheader2*/
	/*   %11 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 5), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_6)) begin
		array_address_a = ((1'd0 + (4 * 32'd5)) >>> 3'd2);
	end
	/* main: %13*/
	/*   store i32 %16, i32* %scevgep6, align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB__13_10)) begin
		array_address_a = (main_13_scevgep6_reg >>> 3'd2);
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %28 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 0), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_12)) begin
		array_address_a = (1'd0 >>> 3'd2);
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %31 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_13)) begin
		array_address_a = ((1'd0 + (4 * 32'd2)) >>> 3'd2);
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %35 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_14)) begin
		array_address_a = ((1'd0 + (4 * 32'd4)) >>> 3'd2);
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %39 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 6), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_15)) begin
		array_address_a = ((1'd0 + (4 * 32'd6)) >>> 3'd2);
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %43 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 8), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_16)) begin
		array_address_a = ((1'd0 + (4 * 32'd8)) >>> 3'd2);
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %47 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 10), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_17)) begin
		array_address_a = ((1'd0 + (4 * 32'd10)) >>> 3'd2);
	end
	/* main: %54*/
	/*   %57 = load i32* %scevgep3, align 4, !tbaa !2, !legup.pipeline.start_time !9, !legup.pipeline.avail_time !10, !legup.pipeline.stage !6
	start_time: 3 avail_time: 4 stage: 1 II: 3 start_ii_state = 3 % 3 = 0 avail_ii_state = 4 % 3 = 1*/
	if (((loop5_1_ii_state == 2'd0) & loop5_1_valid_bit_3)) begin
		array_address_a = (main_54_scevgep3 >>> 3'd2);
	end
end
always @(*) begin
	array_write_enable_a = 1'd0;
	/* main: %.preheader2*/
	/*   %1 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 0), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_1)) begin
		array_write_enable_a = 1'd0;
	end
	/* main: %.preheader2*/
	/*   %3 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_2)) begin
		array_write_enable_a = 1'd0;
	end
	/* main: %.preheader2*/
	/*   %5 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 3), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_3)) begin
		array_write_enable_a = 1'd0;
	end
	/* main: %.preheader2*/
	/*   %7 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_4)) begin
		array_write_enable_a = 1'd0;
	end
	/* main: %.preheader2*/
	/*   %9 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_5)) begin
		array_write_enable_a = 1'd0;
	end
	/* main: %.preheader2*/
	/*   %11 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 5), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_6)) begin
		array_write_enable_a = 1'd0;
	end
	/* main: %13*/
	/*   store i32 %16, i32* %scevgep6, align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB__13_10)) begin
		array_write_enable_a = 1'd1;
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %28 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 0), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_12)) begin
		array_write_enable_a = 1'd0;
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %31 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_13)) begin
		array_write_enable_a = 1'd0;
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %35 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_14)) begin
		array_write_enable_a = 1'd0;
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %39 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 6), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_15)) begin
		array_write_enable_a = 1'd0;
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %43 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 8), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_16)) begin
		array_write_enable_a = 1'd0;
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %47 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 10), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_17)) begin
		array_write_enable_a = 1'd0;
	end
	/* main: %54*/
	/*   %57 = load i32* %scevgep3, align 4, !tbaa !2, !legup.pipeline.start_time !9, !legup.pipeline.avail_time !10, !legup.pipeline.stage !6
	start_time: 3 avail_time: 4 stage: 1 II: 3 start_ii_state = 3 % 3 = 0 avail_ii_state = 4 % 3 = 1*/
	if (((loop5_1_ii_state == 2'd0) & loop5_1_valid_bit_3)) begin
		array_write_enable_a = 1'd0;
	end
end
always @(*) begin
	array_in_a = 1'd0;
	/* main: %13*/
	/*   store i32 %16, i32* %scevgep6, align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB__13_10)) begin
		array_in_a = main_13_16;
	end
end
always @(*) begin
	array_address_b = 1'd0;
	/* main: %.preheader2*/
	/*   %2 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 1), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_1)) begin
		array_address_b = ((1'd0 + (4 * 32'd1)) >>> 3'd2);
	end
	/* main: %.preheader2*/
	/*   %4 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_2)) begin
		array_address_b = ((1'd0 + (4 * 32'd2)) >>> 3'd2);
	end
	/* main: %.preheader2*/
	/*   %6 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_3)) begin
		array_address_b = ((1'd0 + (4 * 32'd4)) >>> 3'd2);
	end
	/* main: %.preheader2*/
	/*   %8 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 3), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_4)) begin
		array_address_b = ((1'd0 + (4 * 32'd3)) >>> 3'd2);
	end
	/* main: %.preheader2*/
	/*   %10 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_5)) begin
		array_address_b = ((1'd0 + (4 * 32'd4)) >>> 3'd2);
	end
	/* main: %.preheader2*/
	/*   %12 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 6), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_6)) begin
		array_address_b = ((1'd0 + (4 * 32'd6)) >>> 3'd2);
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %29 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 1), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_12)) begin
		array_address_b = ((1'd0 + (4 * 32'd1)) >>> 3'd2);
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %33 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 3), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_13)) begin
		array_address_b = ((1'd0 + (4 * 32'd3)) >>> 3'd2);
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %37 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 5), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_14)) begin
		array_address_b = ((1'd0 + (4 * 32'd5)) >>> 3'd2);
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %41 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 7), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_15)) begin
		array_address_b = ((1'd0 + (4 * 32'd7)) >>> 3'd2);
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %45 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 9), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_16)) begin
		array_address_b = ((1'd0 + (4 * 32'd9)) >>> 3'd2);
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %49 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 11), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_17)) begin
		array_address_b = ((1'd0 + (4 * 32'd11)) >>> 3'd2);
	end
	/* main: %54*/
	/*   %58 = load i32* %scevgep2, align 4, !tbaa !2, !legup.pipeline.start_time !9, !legup.pipeline.avail_time !10, !legup.pipeline.stage !6
	start_time: 3 avail_time: 4 stage: 1 II: 3 start_ii_state = 3 % 3 = 0 avail_ii_state = 4 % 3 = 1*/
	if (((loop5_1_ii_state == 2'd0) & loop5_1_valid_bit_3)) begin
		array_address_b = (main_54_scevgep2_reg_stage1 >>> 3'd2);
	end
	/* main: %54*/
	/*   store i32 %59, i32* %scevgep, align 4, !tbaa !2, !legup.pipeline.start_time !11, !legup.pipeline.avail_time !12, !legup.pipeline.stage !6
	start_time: 5 avail_time: 6 stage: 1 II: 3 start_ii_state = 5 % 3 = 2 avail_ii_state = 6 % 3 = 0*/
	if (((loop5_1_ii_state == 2'd2) & loop5_1_valid_bit_5)) begin
		array_address_b = (main_54_scevgep_reg_stage1 >>> 3'd2);
	end
end
always @(*) begin
	array_write_enable_b = 1'd0;
	/* main: %.preheader2*/
	/*   %2 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 1), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_1)) begin
		array_write_enable_b = 1'd0;
	end
	/* main: %.preheader2*/
	/*   %4 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 2), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_2)) begin
		array_write_enable_b = 1'd0;
	end
	/* main: %.preheader2*/
	/*   %6 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_3)) begin
		array_write_enable_b = 1'd0;
	end
	/* main: %.preheader2*/
	/*   %8 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 3), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_4)) begin
		array_write_enable_b = 1'd0;
	end
	/* main: %.preheader2*/
	/*   %10 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 4), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_5)) begin
		array_write_enable_b = 1'd0;
	end
	/* main: %.preheader2*/
	/*   %12 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 6), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_preheader2_6)) begin
		array_write_enable_b = 1'd0;
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %29 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 1), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_12)) begin
		array_write_enable_b = 1'd0;
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %33 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 3), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_13)) begin
		array_write_enable_b = 1'd0;
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %37 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 5), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_14)) begin
		array_write_enable_b = 1'd0;
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %41 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 7), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_15)) begin
		array_write_enable_b = 1'd0;
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %45 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 9), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_16)) begin
		array_write_enable_b = 1'd0;
	end
	/* main: %.lr.ph.i.preheader*/
	/*   %49 = load i32* getelementptr inbounds ([100 x i32]* @array, i32 0, i32 11), align 4, !tbaa !2*/
	if ((cur_state == LEGUP_F_main_BB_lrphipreheader_17)) begin
		array_write_enable_b = 1'd0;
	end
	/* main: %54*/
	/*   %58 = load i32* %scevgep2, align 4, !tbaa !2, !legup.pipeline.start_time !9, !legup.pipeline.avail_time !10, !legup.pipeline.stage !6
	start_time: 3 avail_time: 4 stage: 1 II: 3 start_ii_state = 3 % 3 = 0 avail_ii_state = 4 % 3 = 1*/
	if (((loop5_1_ii_state == 2'd0) & loop5_1_valid_bit_3)) begin
		array_write_enable_b = 1'd0;
	end
	/* main: %54*/
	/*   store i32 %59, i32* %scevgep, align 4, !tbaa !2, !legup.pipeline.start_time !11, !legup.pipeline.avail_time !12, !legup.pipeline.stage !6
	start_time: 5 avail_time: 6 stage: 1 II: 3 start_ii_state = 5 % 3 = 2 avail_ii_state = 6 % 3 = 0*/
	if (((loop5_1_ii_state == 2'd2) & loop5_1_valid_bit_5)) begin
		array_write_enable_b = 1'd1;
	end
end
always @(*) begin
	array_in_b = 1'd0;
	/* main: %54*/
	/*   store i32 %59, i32* %scevgep, align 4, !tbaa !2, !legup.pipeline.start_time !11, !legup.pipeline.avail_time !12, !legup.pipeline.stage !6
	start_time: 5 avail_time: 6 stage: 1 II: 3 start_ii_state = 5 % 3 = 2 avail_ii_state = 6 % 3 = 0*/
	if (((loop5_1_ii_state == 2'd2) & loop5_1_valid_bit_5)) begin
		array_in_b = main_54_59;
	end
end
always @(*) begin
	loop5_1_pipeline_start = 1'd0;
	if (reset) begin
		loop5_1_pipeline_start = 1'd0;
	end
	if (((cur_state == LEGUP_F_main_BB_preheader2_7) & (memory_controller_waitrequest == 1'd0))) begin
		loop5_1_pipeline_start = 1'd1;
	end
end
always @(posedge clk) begin
	if (reset) begin
		loop5_1_started <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_started"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop5_1_pipeline_start & ~(loop5_1_started)))) begin
		loop5_1_started <= 1'd1;
		if (start == 1'b0 && ^(1'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_started"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop5_1_epilogue & (~(loop5_1_valid_bit_5) & loop5_1_valid_bit_6)))) begin
		loop5_1_started <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_started"); $finish; end
	end
end
always @(posedge clk) begin
	if (reset) begin
		loop5_1_ii_state <= 2'd0;
		if (start == 1'b0 && ^(2'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_ii_state"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop5_1_pipeline_start & ~(loop5_1_started)))) begin
		loop5_1_ii_state <= 2'd0;
		if (start == 1'b0 && ^(2'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_ii_state"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop5_1_ii_state == 2'd0))) begin
		loop5_1_ii_state <= 2'd1;
		if (start == 1'b0 && ^(2'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_ii_state"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop5_1_ii_state == 2'd1))) begin
		loop5_1_ii_state <= 2'd2;
		if (start == 1'b0 && ^(2'd2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_ii_state"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop5_1_ii_state == 2'd2))) begin
		loop5_1_ii_state <= 2'd0;
		if (start == 1'b0 && ^(2'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_ii_state"); $finish; end
	end
end
always @(posedge clk) begin
	if (reset) begin
		loop5_1_i_stage0 <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_i_stage0"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop5_1_pipeline_start & ~(loop5_1_started)))) begin
		loop5_1_i_stage0 <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_i_stage0"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (((memory_controller_waitrequest == 1'd0) & (loop5_1_ii_state == 2'd2)) & loop5_1_valid_bit_2))) begin
		loop5_1_i_stage0 <= (loop5_1_i_stage0 + 1'd1);
		if (start == 1'b0 && ^((loop5_1_i_stage0 + 1'd1)) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_i_stage0"); $finish; end
	end
	if (reset) begin
		loop5_1_i_stage0 <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_i_stage0"); $finish; end
	end
end
always @(posedge clk) begin
	if (reset) begin
		loop5_1_epilogue <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_epilogue"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop5_1_started & ((loop5_1_ii_state == 2'd0) & loop5_1_pipeline_exit_cond)))) begin
		loop5_1_epilogue <= 1'd1;
		if (start == 1'b0 && ^(1'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_epilogue"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop5_1_epilogue & (~(loop5_1_valid_bit_5) & loop5_1_valid_bit_6)))) begin
		loop5_1_epilogue <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_epilogue"); $finish; end
	end
end
always @(posedge clk) begin
	if ((memory_controller_waitrequest == 1'd0)) begin
		loop5_1_valid_bit_0 <= (((memory_controller_waitrequest == 1'd0) & (loop5_1_pipeline_start & ~(loop5_1_started))) | ((loop5_1_started & ~(loop5_1_epilogue)) & ~(((memory_controller_waitrequest == 1'd0) & (loop5_1_started & ((loop5_1_ii_state == 2'd0) & loop5_1_pipeline_exit_cond))))));
		if (start == 1'b0 && ^((((memory_controller_waitrequest == 1'd0) & (loop5_1_pipeline_start & ~(loop5_1_started))) | ((loop5_1_started & ~(loop5_1_epilogue)) & ~(((memory_controller_waitrequest == 1'd0) & (loop5_1_started & ((loop5_1_ii_state == 2'd0) & loop5_1_pipeline_exit_cond))))))) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_valid_bit_0"); $finish; end
	end
	if (reset) begin
		loop5_1_valid_bit_0 <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_valid_bit_0"); $finish; end
	end
end
always @(posedge clk) begin
	if ((memory_controller_waitrequest == 1'd0)) begin
		loop5_1_valid_bit_1 <= loop5_1_valid_bit_0;
		if (start == 1'b0 && ^(loop5_1_valid_bit_0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_valid_bit_1"); $finish; end
	end
	if (reset) begin
		loop5_1_valid_bit_1 <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_valid_bit_1"); $finish; end
	end
end
always @(posedge clk) begin
	if ((memory_controller_waitrequest == 1'd0)) begin
		loop5_1_valid_bit_2 <= loop5_1_valid_bit_1;
		if (start == 1'b0 && ^(loop5_1_valid_bit_1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_valid_bit_2"); $finish; end
	end
	if (reset) begin
		loop5_1_valid_bit_2 <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_valid_bit_2"); $finish; end
	end
end
always @(posedge clk) begin
	if ((memory_controller_waitrequest == 1'd0)) begin
		loop5_1_valid_bit_3 <= loop5_1_valid_bit_2;
		if (start == 1'b0 && ^(loop5_1_valid_bit_2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_valid_bit_3"); $finish; end
	end
	if (reset) begin
		loop5_1_valid_bit_3 <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_valid_bit_3"); $finish; end
	end
end
always @(posedge clk) begin
	if ((memory_controller_waitrequest == 1'd0)) begin
		loop5_1_valid_bit_4 <= loop5_1_valid_bit_3;
		if (start == 1'b0 && ^(loop5_1_valid_bit_3) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_valid_bit_4"); $finish; end
	end
	if (reset) begin
		loop5_1_valid_bit_4 <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_valid_bit_4"); $finish; end
	end
end
always @(posedge clk) begin
	if ((memory_controller_waitrequest == 1'd0)) begin
		loop5_1_valid_bit_5 <= loop5_1_valid_bit_4;
		if (start == 1'b0 && ^(loop5_1_valid_bit_4) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_valid_bit_5"); $finish; end
	end
	if (reset) begin
		loop5_1_valid_bit_5 <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_valid_bit_5"); $finish; end
	end
end
always @(posedge clk) begin
	if ((memory_controller_waitrequest == 1'd0)) begin
		loop5_1_valid_bit_6 <= loop5_1_valid_bit_5;
		if (start == 1'b0 && ^(loop5_1_valid_bit_5) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_valid_bit_6"); $finish; end
	end
	if (reset) begin
		loop5_1_valid_bit_6 <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_valid_bit_6"); $finish; end
	end
end
always @(posedge clk) begin
	if (((memory_controller_waitrequest == 1'd0) & (loop5_1_pipeline_start & ~(loop5_1_started)))) begin
		loop5_1_i_stage1 <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_i_stage1"); $finish; end
	end
	if (((memory_controller_waitrequest == 1'd0) & (loop5_1_ii_state == 2'd2))) begin
		loop5_1_i_stage1 <= loop5_1_i_stage0;
		if (start == 1'b0 && ^(loop5_1_i_stage0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_i_stage1"); $finish; end
	end
	if (reset) begin
		loop5_1_i_stage1 <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to loop5_1_i_stage1"); $finish; end
	end
end
always @(posedge clk) begin
	if (((memory_controller_waitrequest == 1'd0) & ((loop5_1_ii_state == 2'd2) & loop5_1_valid_bit_2))) begin
		main_54_55_reg_stage1 <= main_54_55;
		if (start == 1'b0 && ^(main_54_55) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_55_reg_stage1"); $finish; end
	end
end
always @(posedge clk) begin
	if (((memory_controller_waitrequest == 1'd0) & ((loop5_1_ii_state == 2'd0) & loop5_1_valid_bit_3))) begin
		main_54_scevgep_reg_stage1 <= main_54_scevgep;
		if (start == 1'b0 && ^(main_54_scevgep) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_scevgep_reg_stage1"); $finish; end
	end
end
always @(posedge clk) begin
	if (((memory_controller_waitrequest == 1'd0) & ((loop5_1_ii_state == 2'd0) & loop5_1_valid_bit_0))) begin
		main_54_scevgep2_reg_stage0 <= main_54_scevgep2;
		if (start == 1'b0 && ^(main_54_scevgep2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_scevgep2_reg_stage0"); $finish; end
	end
end
always @(posedge clk) begin
	if (((memory_controller_waitrequest == 1'd0) & ((loop5_1_ii_state == 2'd2) & loop5_1_valid_bit_2))) begin
		main_54_scevgep2_reg_stage1 <= main_54_scevgep2_reg_stage0;
		if (start == 1'b0 && ^(main_54_scevgep2_reg_stage0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_scevgep2_reg_stage1"); $finish; end
	end
end
always @(posedge clk) begin
	if (((memory_controller_waitrequest == 1'd0) & ((loop5_1_ii_state == 2'd1) & loop5_1_valid_bit_1))) begin
		main_54_56_reg_stage0 <= main_54_56;
		if (start == 1'b0 && ^(main_54_56) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_56_reg_stage0"); $finish; end
	end
end
always @(posedge clk) begin
	if (((memory_controller_waitrequest == 1'd0) & ((loop5_1_ii_state == 2'd2) & loop5_1_valid_bit_2))) begin
		main_54_56_reg_stage1 <= main_54_56_reg_stage0;
		if (start == 1'b0 && ^(main_54_56_reg_stage0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_54_56_reg_stage1"); $finish; end
	end
end
always @(*) begin
	loop5_1_pipeline_exit_cond = (loop5_1_i_stage0 == 97);
end
always @(*) begin
	loop5_1_pipeline_finish = ((memory_controller_waitrequest == 1'd0) & (loop5_1_epilogue & (~(loop5_1_valid_bit_5) & loop5_1_valid_bit_6)));
end
always @(*) begin
	lpm_mult_main_13_15_en = (memory_controller_waitrequest == 1'd0);
end
always @(posedge clk) begin
	/* main: %13*/
	/*   %15 = mul nsw i32 %14, %i.010*/
	if ((lpm_mult_main_13_15_en == 1'd1)) begin
		main_13_15_stage0_reg <= (main_13_14 * main_13_i010_reg);
	end
end
always @(*) begin
	lpm_mult_main_54_59_en = (memory_controller_waitrequest == 1'd0);
end
always @(posedge clk) begin
	/* main: %54*/
	/*   %59 = mul nsw i32 %58, %57, !legup.pipeline.start_time !10, !legup.pipeline.avail_time !11, !legup.pipeline.stage !6
	start_time: 4 avail_time: 5 stage: 1 II: 3 start_ii_state = 4 % 3 = 1 avail_ii_state = 5 % 3 = 2*/
	if ((lpm_mult_main_54_59_en == 1'd1)) begin
		main_54_59_stage0_reg <= (main_54_58 * main_54_57);
	end
end
always @(posedge clk) begin
	if ((cur_state == LEGUP_0)) begin
		finish <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to finish"); $finish; end
	end
	/* main: %64*/
	/*   ret i32 %51*/
	if ((cur_state == LEGUP_F_main_BB__64_38)) begin
		finish <= (memory_controller_waitrequest == 1'd0);
		if (start == 1'b0 && ^((memory_controller_waitrequest == 1'd0)) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to finish"); $finish; end
	end
end
always @(posedge clk) begin
	if ((cur_state == LEGUP_0)) begin
		return_val <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to return_val"); $finish; end
	end
	/* main: %64*/
	/*   ret i32 %51*/
	if ((cur_state == LEGUP_F_main_BB__64_38)) begin
		return_val <= main_lrphipreheader_51_reg;
		if (start == 1'b0 && ^(main_lrphipreheader_51_reg) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to return_val"); $finish; end
	end
end

endmodule 
module ram_dual_port
(
	clk,
	clken,
	address_a,
	address_b,
	wren_a,
	wren_b,
	data_a,
	data_b,
	byteena_a,
	byteena_b,
	q_a,
	q_b
);

parameter  width_a = 1'd0;
parameter  width_b = 1'd0;
parameter  widthad_a = 1'd0;
parameter  widthad_b = 1'd0;
parameter  numwords_a = 1'd0;
parameter  numwords_b = 1'd0;
parameter  init_file = "UNUSED.mif";
parameter  width_be_a = 1'd0;
parameter  width_be_b = 1'd0;
parameter  latency = 1;

input  clk;
input  clken;
input [(widthad_a-1):0] address_a;
input [(widthad_b-1):0] address_b;
output wire [(width_a-1):0] q_a;
output wire [(width_b-1):0] q_b;
reg [(width_a-1):0] q_a_wire;
reg [(width_b-1):0] q_b_wire;
input  wren_a;
input  wren_b;
input [(width_a-1):0] data_a;
input [(width_b-1):0] data_b;
// byte enable is unsupported by inferred RAMs
input [width_be_a-1:0] byteena_a;
input [width_be_b-1:0] byteena_b;

(* ramstyle = "no_rw_check", ram_init_file = init_file *) reg [width_a-1:0] ram[numwords_a-1:0];

/* synthesis translate_off */
integer i;
ALTERA_MF_MEMORY_INITIALIZATION mem ();
reg [8*256:1] ram_ver_file;
initial begin
	if (init_file == "UNUSED.mif")
    begin
		for (i = 0; i < numwords_a; i = i + 1)
			ram[i] = 0;
    end
	else
    begin
        // modelsim can't read .mif files directly. So use Altera function to
        // convert them to .ver files
        mem.convert_to_ver_file(init_file, width_a, ram_ver_file);
        $readmemh(ram_ver_file, ram);
    end
end
/* synthesis translate_on */

always @ (posedge clk)
if (clken)
begin // Port A
if (wren_a)
begin
    ram[address_a] <= data_a;
    q_a_wire <= {width_a{1'bX}};
end
else
    q_a_wire <= ram[address_a];
end
always @ (posedge clk)
if (clken)
begin // Port b
if (wren_b)
begin
    ram[address_b] <= data_b;
    q_b_wire <= {width_b{1'bX}};
end
else
    q_b_wire <= ram[address_b];
end



integer j;
reg [(width_a-1):0] q_a_reg[latency:1], q_b_reg[latency:1];

always @(*)
begin
   q_a_reg[1] <= q_a_wire;
   q_b_reg[1] <= q_b_wire;
end

always @(posedge clk)
if (clken)
begin
   for (j = 1; j < latency; j=j+1)
   begin
       q_a_reg[j+1] <= q_a_reg[j];
       q_b_reg[j+1] <= q_b_reg[j];
   end
end

assign q_a = (clken) ? q_a_reg[latency] : 0;
assign q_b = (clken) ? q_b_reg[latency] : 0;


endmodule
module rom_dual_port
(
	clk,
	clken,
	address_a,
	address_b,
	q_a,
	q_b
);

parameter  width_a = 1'd0;
parameter  width_b = 1'd0;
parameter  widthad_a = 1'd0;
parameter  widthad_b = 1'd0;
parameter  numwords_a = 1'd0;
parameter  numwords_b = 1'd0;
parameter  init_file = "UNUSED.mif";
parameter  latency = 1;

input  clk;
input  clken;
input [(widthad_a-1):0] address_a;
input [(widthad_b-1):0] address_b;
output wire [(width_a-1):0] q_a;
output wire [(width_b-1):0] q_b;
reg [(width_a-1):0] q_a_wire;
reg [(width_b-1):0] q_b_wire;

(* ramstyle = "no_rw_check", ram_init_file = init_file *) reg [width_a-1:0] ram[numwords_a-1:0];

/* synthesis translate_off */
integer i;
ALTERA_MF_MEMORY_INITIALIZATION mem ();
reg [8*256:1] ram_ver_file;
initial begin
	if (init_file == "UNUSED.mif")
    begin
		for (i = 0; i < numwords_a; i = i + 1)
			ram[i] = 0;
    end
	else
    begin
        // modelsim can't read .mif files directly. So use Altera function to
        // convert them to .ver files
        mem.convert_to_ver_file(init_file, width_a, ram_ver_file);
        $readmemh(ram_ver_file, ram);
    end
end
/* synthesis translate_on */

always @ (posedge clk)
if (clken)
begin
    q_a_wire <= ram[address_a];
    q_b_wire <= ram[address_b];
end



integer j;
reg [(width_a-1):0] q_a_reg[latency:1], q_b_reg[latency:1];

always @(*)
begin
   q_a_reg[1] <= q_a_wire;
   q_b_reg[1] <= q_b_wire;
end

always @(posedge clk)
if (clken)
begin
   for (j = 1; j < latency; j=j+1)
   begin
       q_a_reg[j+1] <= q_a_reg[j];
       q_b_reg[j+1] <= q_b_reg[j];
   end
end

assign q_a = (clken) ? q_a_reg[latency] : 0;
assign q_b = (clken) ? q_b_reg[latency] : 0;


endmodule
// Adding code from verilog file: /home/leandro/myLegUp/4.0/examples/../boards/CycloneII/DE2/top.v


module de2 (
	    CLOCK_50,
	    KEY,
	    SW,
	    HEX0,
	    HEX1,
	    HEX2,
	    HEX3,
	    HEX4,
	    HEX5,
	    HEX6,
	    HEX7,
	    LEDG,
		UART_RXD,
		UART_TXD

	    );

   input CLOCK_50;
   input [3:0] KEY;
   input [17:0] SW;
   output [6:0] HEX0, HEX1,  HEX2,  HEX3,  HEX4,  HEX5,  HEX6,  HEX7;
   reg [6:0] 	hex0, hex1, hex2, hex3, hex4, hex5, hex6, hex7;
   

   output [7:0] LEDG;
    input UART_RXD;
    output UART_TXD;    
	wire clk = CLOCK_50;
	wire go = ~KEY[1];



   wire 	reset = ~KEY[0];
   wire 	start;
   wire [31:0] 	return_val;
   reg  [31:0] 	return_val_reg;
   wire 	finish;
   wire [3:0]	state;

   hex_digits h7( .x(hex7), .hex_LEDs(HEX7));
   hex_digits h6( .x(hex6), .hex_LEDs(HEX6));
   hex_digits h5( .x(hex5), .hex_LEDs(HEX5));
   hex_digits h4( .x(hex4), .hex_LEDs(HEX4));
   hex_digits h3( .x(hex3), .hex_LEDs(HEX3));
   hex_digits h2( .x(hex2), .hex_LEDs(HEX2));
   hex_digits h1( .x(hex1), .hex_LEDs(HEX1));
   hex_digits h0( .x(hex0), .hex_LEDs(HEX0));
   
	always @ (*) begin
		hex7 <= return_val_reg[31:28];
		hex6 <= return_val_reg[27:24];
		hex5 <= return_val_reg[23:20];
		hex4 <= return_val_reg[19:16];
		hex3 <= return_val_reg[15:12];
		hex2 <= return_val_reg[11:8];
		hex1 <= return_val_reg[7:4];
		hex0 <= return_val_reg[3:0];
	end
assign UART_TXD = 1'b0;

    parameter s_WAIT = 3'b001, s_START = 3'b010, s_EXE = 3'b011,
                s_DONE = 3'b100;

    // state registers
    reg [3:0] y_Q, Y_D;

    assign LEDG[3:0] = y_Q;

    // next state
    always @(*)
    begin
        case (y_Q)
            s_WAIT: if (go) Y_D = s_START; else Y_D = y_Q;

            s_START: Y_D = s_EXE;

            s_EXE: if (!finish) Y_D = s_EXE; else Y_D = s_DONE;

            s_DONE: Y_D = s_DONE;

            default: Y_D = 3'bxxx;
        endcase
    end

    // current state
    always @(posedge clk)
    begin
        if (reset) // synchronous clear
            y_Q <= s_WAIT;
        else
            y_Q <= Y_D;
    end

    always @(posedge clk)
        if (y_Q == s_EXE && finish)
            return_val_reg <= return_val;
        else if (y_Q == s_DONE)
            return_val_reg <= return_val_reg;
        else
            return_val_reg <= 0;


    assign start = (y_Q == s_START);

   
   top top_inst (
      .clk (clk),
      .reset (reset),
      .finish (finish),
      .return_val (return_val),
        .start (start)

    );

endmodule

// Adding code from verilog file: /home/leandro/myLegUp/4.0/examples/../boards/StratixIV/DE4/top.v


module de4 ( 
    	     OSC_50_BANK2, 
             BUTTON, 
             LED, 
    	     SEG0_D, 
    	     SEG1_D 
	     ); 
   input OSC_50_BANK2; 
   input [1:0] BUTTON; 
   output [6:0] SEG0_D; 
   output [6:0] SEG1_D; 
   output [7:0] LED; 
   
   de2 de2_inst ( 
		  .CLOCK_50 (OSC_50_BANK2), 
		  .LEDG (LED), 
		  .KEY (BUTTON), 
		  .SW (), 
		  .HEX0 (SEG0_D), 
		  .HEX1 (SEG1_D), 
		  .HEX2 (), 
		  .HEX3 (), 
		  .HEX4 (), 
		  .HEX5 (), 
		  .HEX6 (), 
		  .HEX7 () 
		  ); 
   
endmodule
// Adding code from verilog file: /home/leandro/myLegUp/4.0/examples/../boards/Virtex6/ML605/top.v


module ML605 (
       USER_CLOCK,
	    KEY,
	    SW,	    
       LED,
       LEDG,
		UART_RXD,
		UART_TXD

	    );

   input USER_CLOCK;
   input [4:0] KEY;
   input [7:0] SW;
   output [7:0] LED;
   output [7:0] LEDG;
   wire CLOCK_50;

    input UART_RXD;
    output UART_TXD;    
	wire clk = CLOCK_50;
	wire go = ~KEY[1];



   wire 	reset = ~KEY[0];
   wire 	start;
   wire [31:0] 	return_val;
   reg  [31:0] 	return_val_reg;
   wire 	finish;
   wire [3:0]	state;
   
   reg [6:0]   hex0, hex1, hex2, hex3, hex4, hex5, hex6, hex7;

   assign CLOCK_50 = USER_CLOCK;
   assign LED = 0;
   
	always @ (*) begin
		hex7 <= return_val_reg[31:28];
		hex6 <= return_val_reg[27:24];
		hex5 <= return_val_reg[23:20];
		hex4 <= return_val_reg[19:16];
		hex3 <= return_val_reg[15:12];
		hex2 <= return_val_reg[11:8];
		hex1 <= return_val_reg[7:4];
		hex0 <= return_val_reg[3:0];
	end
assign UART_TXD = 1'b0;

    parameter s_WAIT = 3'b001, s_START = 3'b010, s_EXE = 3'b011,
                s_DONE = 3'b100;

    // state registers
    reg [3:0] y_Q, Y_D;

    assign LEDG[3:0] = y_Q;

    // next state
    always @(*)
    begin
        case (y_Q)
            s_WAIT: if (go) Y_D = s_START; else Y_D = y_Q;

            s_START: Y_D = s_EXE;

            s_EXE: if (!finish) Y_D = s_EXE; else Y_D = s_DONE;

            s_DONE: Y_D = s_DONE;

            default: Y_D = 3'bxxx;
        endcase
    end

    // current state
    always @(posedge clk)
    begin
        if (reset) // synchronous clear
            y_Q <= s_WAIT;
        else
            y_Q <= Y_D;
    end

    always @(posedge clk)
        if (y_Q == s_EXE && finish)
            return_val_reg <= return_val;
        else if (y_Q == s_DONE)
            return_val_reg <= return_val_reg;
        else
            return_val_reg <= 0;


    assign start = (y_Q == s_START);

   
   top top_inst (
      .clk (clk),
      .reset (reset),
      .finish (finish),
      .return_val (return_val),
        .start (start)

    );

   

endmodule

module circuit_start_control (
    go,
    control_key
);
    input control_key;
    output go;
    assign go = control_key;
endmodule
module hex_digits(x, hex_LEDs);
    input [3:0] x;
    output [6:0] hex_LEDs;
    
    assign hex_LEDs[0] = (~x[3] & ~x[2] & ~x[1] & x[0]) |
                            (~x[3] & x[2] & ~x[1] & ~x[0]) |
                            (x[3] & x[2] & ~x[1] & x[0]) |
                            (x[3] & ~x[2] & x[1] & x[0]);
    assign hex_LEDs[1] = (~x[3] & x[2] & ~x[1] & x[0]) |
                            (x[3] & x[1] & x[0]) |
                            (x[3] & x[2] & ~x[0]) |
                            (x[2] & x[1] & ~x[0]);
    assign hex_LEDs[2] = (x[3] & x[2] & ~x[0]) |
                            (x[3] & x[2] & x[1]) |
                            (~x[3] & ~x[2] & x[1] & ~x[0]);
    assign hex_LEDs[3] = (~x[3] & ~x[2] & ~x[1] & x[0]) | 
                            (~x[3] & x[2] & ~x[1] & ~x[0]) | 
                            (x[2] & x[1] & x[0]) | 
                            (x[3] & ~x[2] & x[1] & ~x[0]);
    assign hex_LEDs[4] = (~x[3] & x[0]) |
                            (~x[3] & x[2] & ~x[1]) |
                            (~x[2] & ~x[1] & x[0]);
    assign hex_LEDs[5] = (~x[3] & ~x[2] & x[0]) | 
                            (~x[3] & ~x[2] & x[1]) | 
                            (~x[3] & x[1] & x[0]) | 
                            (x[3] & x[2] & ~x[1] & x[0]);
    assign hex_LEDs[6] = (~x[3] & ~x[2] & ~x[1]) | 
                            (x[3] & x[2] & ~x[1] & ~x[0]) | 
                            (~x[3] & x[2] & x[1] & x[0]);
    
endmodule
`timescale 1 ns / 1 ns
module main_tb
(
);

reg  clk;
reg  reset;
reg  start;
reg  waitrequest;
wire [31:0] return_val;
wire  finish;


top top_inst (
	.clk (clk),
	.reset (reset),
	.start (start),
	.waitrequest (waitrequest),
	.finish (finish),
	.return_val (return_val)
);


// Local Rams



initial 
    clk = 0;
always @(clk)
    clk <= #10 ~clk;

initial begin
//$monitor("At t=%t clk=%b %b %b %b %d", $time, clk, reset, start, finish, return_val);
@(negedge clk);
reset <= 1;
@(negedge clk);
reset <= 0;
start <= 1;
@(negedge clk);
start <= 0;
end

always@(finish) begin
    if (finish == 1) begin
        $display("At t=%t clk=%b finish=%b return_val=%d", $time, clk, finish, return_val);
        $display("Cycles: %d", ($time-50)/20);
        $finish;
    end
end

initial begin
waitrequest <= 1;
@(negedge clk);
@(negedge clk);
waitrequest <= 0;
end


endmodule 
