NAME=module
CUSTOM_MODULE_SCHEDULING = 1
NO_OPT=0
NO_INLINE=0
LEVEL = $(LEGUPHOME)/examples
#LOCAL_CONFIG = -legup-config=config1.tcl
CONFIGS=$(shell ls config*.tcl)
include $(LEGUPHOME)/examples/Makefile.loopsFast
