/* confdefs.h */
#define PACKAGE_NAME "LLVM"
#define PACKAGE_TARNAME "llvm"
#define PACKAGE_VERSION "3.5.0"
#define PACKAGE_STRING "LLVM 3.5.0"
#define PACKAGE_BUGREPORT "http://llvm.org/bugs/"
#define PACKAGE_URL ""
#define LLVM_VERSION_MAJOR 3
#define LLVM_VERSION_MINOR 5
#define LLVM_VERSION_PATCH 0
#define LLVM_ON_UNIX 1
#define LLVM_ENABLE_THREADS 1
#define LLVM_ENABLE_ZLIB 1
#define ENABLE_PIC 1
#define ENABLE_TIMESTAMPS 1
#define ENABLE_BACKTRACES 1
#define ENABLE_CRASH_OVERRIDES 1
#define LLVM_NATIVE_ARCH X86
#define LLVM_NATIVE_TARGET LLVMInitializeX86Target
#define LLVM_NATIVE_TARGETINFO LLVMInitializeX86TargetInfo
#define LLVM_NATIVE_TARGETMC LLVMInitializeX86TargetMC
#define LLVM_NATIVE_ASMPRINTER LLVMInitializeX86AsmPrinter
#define LLVM_NATIVE_ASMPARSER LLVMInitializeX86AsmParser
#define LLVM_NATIVE_DISASSEMBLER LLVMInitializeX86Disassembler
#define CLANG_RESOURCE_DIR ""
#define C_INCLUDE_DIRS ""
#define GCC_INSTALL_PREFIX ""
#define DEFAULT_SYSROOT ""
#define BUG_REPORT_URL "http://llvm.org/bugs/"
#define HOST_LINK_VERSION "2.24"
#define HAVE_LINK_R 1
#define HAVE_LINK_EXPORT_DYNAMIC 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_ERRNO_H 1
#define LTDL_SHLIB_EXT ".so"
#define HAVE_LIBM 1
#define HAVE_DLOPEN 1
#define HAVE_TERMINFO 1
#define HAVE_MALLINFO 1
#define HAVE_LIBPTHREAD 1
#define HAVE_PTHREAD_MUTEX_LOCK 1
#define HAVE_PTHREAD_RWLOCK_INIT 1
#define HAVE_PTHREAD_GETSPECIFIC 1
#define HAVE_LIBZ 1
#define LLVM_USE_OPROFILE 0
#define LLVM_USE_INTEL_JITEVENTS 0
#define HAVE_DIRENT_H 1
#define HAVE_MMAP_ANONYMOUS 1
#define HAVE_SYS_WAIT_H 1
#define TIME_WITH_SYS_TIME 1
#define HAVE_CXXABI_H 1
#define HAVE_DLFCN_H 1
#define HAVE_EXECINFO_H 1
#define HAVE_FCNTL_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LINK_H 1
#define HAVE_MALLOC_H 1
#define HAVE_SETJMP_H 1
#define HAVE_SIGNAL_H 1
#define HAVE_STDINT_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_UNISTD_H 1
#define HAVE_UTIME_H 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_RESOURCE_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_UIO_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_FENV_H 1
#define HAVE_DECL_FE_ALL_EXCEPT 1
#define HAVE_DECL_FE_INEXACT 1
#define HAVE_TCL8_5_TCL_H 1
#define HAVE_PTHREAD_H 1
#define HAVE_ZLIB_H 1
#define HAVE_CRASHREPORTER_INFO 0
#define RETSIGTYPE void
#define HAVE_INT64_T 1
#define HAVE_UINT64_T 1
#define HAVE_BACKTRACE 1
#define HAVE_CEILF 1
#define HAVE_FLOORF 1
#define HAVE_ROUNDF 1
#define HAVE_RINTF 1
#define HAVE_NEARBYINTF 1
#define HAVE_GETCWD 1
#define HAVE_POWF 1
#define HAVE_FMODF 1
#define HAVE_STRTOF 1
#define HAVE_ROUND 1
#define HAVE_LOG 1
#define HAVE_LOG2 1
#define HAVE_LOG10 1
#define HAVE_EXP 1
#define HAVE_EXP2 1
#define HAVE_GETPAGESIZE 1
#define HAVE_GETRUSAGE 1
#define HAVE_GETRLIMIT 1
#define HAVE_SETRLIMIT 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_ISATTY 1
#define HAVE_MKDTEMP 1
#define HAVE_MKSTEMP 1
#define HAVE_MKTEMP 1
#define HAVE_POSIX_SPAWN 1
#define HAVE_PREAD 1
#define HAVE_REALPATH 1
#define HAVE_SBRK 1
#define HAVE_SETRLIMIT 1
#define HAVE_STRERROR 1
#define HAVE_STRERROR_R 1
#define HAVE_SETENV 1
#define HAVE_STRTOLL 1
#define HAVE_STRTOQ 1
#define HAVE_SYSCONF 1
#define HAVE_SETJMP 1
#define HAVE_LONGJMP 1
#define HAVE_SIGLONGJMP 1
#define HAVE_WRITEV 1
#define HAVE_FUTIMES 1
#define HAVE_FUTIMENS 1
#define HAVE_PRINTF_A 1
#define HAVE_RAND48 1
#define HAVE_DECL_ARC4RANDOM 0
#define HAVE_DECL_STRERROR_S 0
#define HAVE_ISNAN_IN_MATH_H 1
#define HAVE_ISNAN_IN_CMATH 1
#define HAVE_STD_ISNAN_IN_CMATH 1
#define HAVE_ISINF_IN_MATH_H 1
#define HAVE_ISINF_IN_CMATH 1
#define HAVE_STD_ISINF_IN_CMATH 1
#define HAVE_STDLIB_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_GETPAGESIZE 1
#define HAVE_MMAP 1
#define HAVE_MMAP_FILE /**/
#define LLVM_HAS_ATOMICS 1
#define HAVE___DSO_HANDLE 1
#define LLVM_PREFIX "/usr/local"
#define LLVM_BINDIR "/usr/local/bin"
#define LLVM_DATADIR "/usr/local/share/llvm"
#define LLVM_DOCSDIR "/usr/local/share/doc/llvm"
#define LLVM_ETCDIR "/usr/local/etc/llvm"
#define LLVM_INCLUDEDIR "/usr/local/include"
#define LLVM_INFODIR "/usr/local/info"
#define LLVM_MANDIR "/usr/local/man"
#define LLVM_CONFIGTIME "Mon May 14 17:29:57 -03 2018"
#define LLVM_HOST_TRIPLE "x86_64-unknown-linux-gnu"
#define LLVM_DEFAULT_TARGET_TRIPLE "x86_64-unknown-linux-gnu"
