loop_pipeline "loop6"
set_parameter LOCAL_RAMS 0
set_parameter MODULO_SCHEDULER "NI"
set_resource_constraint signed_add_32 2
set_resource_constraint signed_comp_eq_32 1
set_resource_constraint signed_multiply_32 1
